/*
 * This file is generated by jOOQ.
*/
package jooqEntity;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooqEntity.tables.TUser;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MyScala extends SchemaImpl {

    private static final long serialVersionUID = -583737777;

    /**
     * The reference instance of <code>my_scala</code>
     */
    public static final MyScala MY_SCALA = new MyScala();

    /**
     * The table <code>my_scala.t_user</code>.
     */
    public final TUser T_USER = jooqEntity.tables.TUser.T_USER;

    /**
     * No further instances allowed
     */
    private MyScala() {
        super("my_scala", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TUser.T_USER);
    }
}
