/*
 * This file is generated by jOOQ.
*/
package jooqEntity;


import javax.annotation.Generated;

import jooqEntity.tables.TUser;


/**
 * Convenience access to all tables in my_scala
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>my_scala.t_user</code>.
     */
    public static final TUser T_USER = jooqEntity.tables.TUser.T_USER;
}
