/*
 * This file is generated by jOOQ.
*/
package jooqEntity.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooqEntity.Keys;
import jooqEntity.MyScala;
import jooqEntity.tables.records.TUserRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser extends TableImpl<TUserRecord> {

    private static final long serialVersionUID = -1480187316;

    /**
     * The reference instance of <code>my_scala.t_user</code>
     */
    public static final TUser T_USER = new TUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserRecord> getRecordType() {
        return TUserRecord.class;
    }

    /**
     * The column <code>my_scala.t_user.id</code>. 主键id
     */
    public final TableField<TUserRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "主键id");

    /**
     * The column <code>my_scala.t_user.name</code>. 姓名
     */
    public final TableField<TUserRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "姓名");

    /**
     * The column <code>my_scala.t_user.sex</code>. 性别
     */
    public final TableField<TUserRecord, String> SEX = createField("sex", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "性别");

    /**
     * The column <code>my_scala.t_user.phone</code>. 电话号码
     */
    public final TableField<TUserRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "电话号码");

    /**
     * Create a <code>my_scala.t_user</code> table reference
     */
    public TUser() {
        this("t_user", null);
    }

    /**
     * Create an aliased <code>my_scala.t_user</code> table reference
     */
    public TUser(String alias) {
        this(alias, T_USER);
    }

    private TUser(String alias, Table<TUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUser(String alias, Table<TUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MyScala.MY_SCALA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TUserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TUserRecord> getPrimaryKey() {
        return Keys.KEY_T_USER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TUserRecord>> getKeys() {
        return Arrays.<UniqueKey<TUserRecord>>asList(Keys.KEY_T_USER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUser as(String alias) {
        return new TUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUser rename(String name) {
        return new TUser(name, null);
    }
}
